name = "dispatcher"
main = "src/index.ts"
compatibility_date = "2024-03-20"

[triggers]
crons = ["* * * * *"] # Configured to trigger every minute

[[queues.producers]]
queue = "search-sync-queue"
binding = "SEARCH_SYNC"

[[queues.producers]]
queue = "media-sync-queue"
binding = "MEDIA_SYNC"

[[queues.producers]]
queue = "ai-sync-queue"
binding = "AI_SYNC"
