name = "media-sync"
main = "src/index.ts"
compatibility_date = "2024-03-20"

[[queues.consumers]]
queue = "media-sync-queue"
max_batch_size = 10
max_batch_timeout = 5
max_concurrency = 1

[[kv_namespaces]]
binding = "MEDIA_STATE"
id = "ecb5dab7b2fa4987ab6fb85096e9f2c7"

[observability]
enabled = true
head_sampling_rate = 1
